### ISSUE TITLE
ANUPQ under Cygwin

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/anupq#1]
I was checking if ANUPQ binary can be build and used under Cygwin. I can build it with ./configure ; make on the same machine where GAP kernel and kernel modules for packages are built. Then these binaries are tested on another machine withour Cygwin.

First, loading the package fails as below:
```
gap> LoadPackage("anupq");
The system cannot find the path specified.
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `PositionSublist' on 3 arguments called fr
om
PositionSublist( list, sub, 0 ) called from
<function "unknown">( <arguments> )
called from read-eval loop at line
42 of /cygdrive/c/gap4r7/pkg/anupq-3.1.1/lib/anupqhead.gi
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> list;
fail
brk> sub;
"Version"
brk> ANUPQData;
rec( SPimages := "c:/WINDOWS/Temp/tmfAF6r8/GAP_library",
 binary := "/cygdrive/c/gap4r7/pkg/anupq-3.1.1/bin/i686-pc-cygwin-gcc-default\
32/pq", io := [  ], ni := rec(  ),
 outfile := "c:/WINDOWS/Temp/tmfAF6r8/PQ_OUTPUT",
 tmpdir := dir("c:/WINDOWS/Temp/tmfAF6r8/"), version := fail )
brk>
```
I've tried to change to the directory where pq.exe sits and launch it, and it
fails telling that cygwin1.dll is missing. I've copied the same cygwin1.dll
which is in gap4r7/bin and then it worked:
```
c:\gap4r7\pkg\anupq-3.1.1\bin\i686-pc-cygwin-gcc-default32>pq.exe
ANU p-Quotient Program Version 1.9 running with workspace 10000000 on gapwin7
Mon Nov 25 14:33:40 GMTST 2013
## Basic Menu for p-Quotient Program
1. Compute pc presentation
2. Save presentation to file
3. Restore presentation from file
4. Display presentation of group
5. Set print level
6. Calculate next class
7. Compute p-covering group
8. Advanced p-quotient menu
9. (Main) menu for p-group generation
10. Exit from p-quotient program
    ...
```
However, restarting GAP I am getting the same error as above. Likely the way how
the version is determined in anupqhead.gi is not going to work under Windows, and one has to find a workaround....

**Comment by fingolfin** [comment]
Are there any examples of GAP packages which use an external binary (like anupq does), and which actually do work correctly under Cygwin? That would be good to know, as then one could look at how these packages do things.

**Comment by alex-konovalov** [comment]
@fingolfin yes - at least one I know about is GRAPE. Out of the box under Cygwin32, since the architecture-dependent part of the path is hardcoded there. Under Cygwin64 you need to edit the path in one place first.

**Comment by fingolfin** [comment]
So I am not sure what the issue here is: If I understand you right, you managed to build anupq on a machine with cygwin, and it works there. But what didn't work was copying in to a machine w/o cygwin and using it there.

Well, that's not a surprise. Cygwin is needed. Also GAP needs it, it just bundles its own copy (of the DLL, at least). There isn't much anupq can do about that, other than bundle a copy of that DLL, or simply declare cygwin as a dependency. On the long run, the better solution is to have a GAP package manager / shared package build environment so that all packages can share the same cygwin.dll. But it's not something we are likely to fix in anupq on its own.

**Comment by alex-konovalov** [comment]
Currently in the GAP master branch, when ANUPQ binaries are compiled under Cygwin, and then GAP distribution with them is tested on a Cygwin-free machine (GAP started with `bin/gap.bat`), loading ANUPQ results in the following error:

```
The system cannot find the path specified.
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `+' on 2 arguments
The 1st argument is 'fail' which might point to an earlier problem
 at /proc/cygdrive/C/gap-4.9.0/lib/methsel2.g:250 called from
<function "HANDLE_METHOD_NOT_FOUND">( <arguments> )
 called from read-eval loop at /proc/cygdrive/C/gap-4.9.0/pkg/anupq-3.2/lib/anupqhead.gi:40
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> 
```
This has been reported first in https://github.com/gap-system/gap/issues/1820. For now, in the GAP distribution for Windows, I will remove `anupq-*/bin` directory to ensure that `LoadAllPackages();` works, but it will be nice to fix this in the long run to ensure that `LoadAllPackages();` does not result in a break loop on Windows without any povisional arrangements.

One possible fix could be to use `ExternalFilename` like GRAPE package does, but see https://github.com/gap-system/gap/issues/2023 regarding this.

**Comment by fingolfin** [comment]
I pushed a commit which changes the code to use `ExternalFilename`, but I have no means to test it on Cygwin. If somebody could test it and report back, that'd be great.

**Comment by fingolfin** [comment]
@alex-konovalov can you perhaps confirm whether the fix in `master` indeed solves the cygwin problem for you?

**Comment by alex-konovalov** [comment]
No, it doesn't:
```
'C:\cygwin\home\alexk\GITREPS\gap\pkg\anupq\bin\i686-pc-cygwin-default32-kv6\pq' is not recognized as an internal or external command,
operable program or batch file.
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `+' on 2 arguments
The 1st argument is 'fail' which might point to an earlier problem
 at /proc/cygdrive/C/cygwin/home/alexk/GITREPS/gap/lib/methsel2.g:249 called from
<function "HANDLE_METHOD_NOT_FOUND">( <arguments> )
 called from read-eval loop at /proc/cygdrive/C/cygwin/home/alexk/GITREPS/gap/pkg/anupq/lib/anupqhead.gi:40
type 'quit;' to quit to outer loop
brk> 
```

**Comment by fingolfin** [comment]
There is nothing I can do about this. Patches welcome.

**Comment by mkeilberg** [comment]
I had the same problem today, and fixed it with the following code.  The short of the matter is that we apparently need to use the more general Process command rather than the Exec command, which in turn lets us ditch the ExternalFilename call for a Filename.

`InstallValue( ANUPQData,
  rec( binary := Filename( DirectoriesPackagePrograms( "anupq" ), "pq" ),
       tmpdir := DirectoryTemporary(),
       ni := rec(), # record for non-interactive functions
       io := []     # list of records for PqStart IO Streams,
                    #  of which, there are initially none
       )
);
ANUPQData.outfile  := Filename( ANUPQData.tmpdir, "PQ_OUTPUT" );
ANUPQData.SPimages := Filename( ANUPQData.tmpdir, "GAP_library" );

# Fire up the pq binary to get its version
Process(DirectoryCurrent(),ANUPQData.binary,InputTextUser(),OutputTextFile(ANUPQData.outfile,false),["-v"]);
ANUPQData.version := StringFile( ANUPQData.outfile );
ANUPQData.version := 
    ANUPQData.version{[PositionSublist( ANUPQData.version, "Version" ) + 8 ..
                       Length(ANUPQData.version) - 1] };`

**Comment by fingolfin** [comment]
@mkeilberg thanks. Yes, that's right; it was fixed this way in March, see ee765c7a9e86eb213b29abf6e575188c2e0ef59f, but I have not yet made a new release (I was waiting for @ChrisJefferson or @alex-konovalov to test it, and then it got forgotten)

**Comment by mkeilberg** [comment]
I suspected something like that was the case when I went to figure out how I might make the pull request for it and saw the code was already of this same form (despite having the issue after just downloading a fresh gap 4.11.0 install).  Glad it's getting the attention needed for closing.

**Comment by alex-konovalov** [comment]
It's now loadable under Windows in GAP 4.11.1.
