### ISSUE TITLE
not enough ttys

### ISSUE THREAD

**Issue by heikodietrich** [gap-packages/anupq#11]
The third error I'm reporting is even more vague: when doing a lot of calls to PqDescendant (and storing the groups), then at some stage an error message "not enough ttys" (or similar) shows up. This usually happens after computations have run for a day or so (-- so unfortunately I cannot give more details right now). I hope the type of error indicates where this is coming from...

**Comment by fingolfin** [comment]
This sounds as if GAP resp. the anupq package is starting many child processes, but does not properly close the connection to them, resulting in leaked (p)ttys, and then final an error, as it runs out of available resources.
I have long suspected that something is buggy in the anupq package in this regard, but never managed to track it down (though I fixed at least one related bug in GAP a few years ago).

Not very helpful, I know :/

**Comment by fingolfin** [comment]
See also #15 -- hmm, I wonder if you could provide the `config.h` file of *GAP* on the machine where you had / have the issue? I would like to know which of HAVE_POSIX_OPENPT / HAVE_PTSNAME / HAVE_GETPT / HAVE_PTSNAME_R / ... are set

**Comment by alex-konovalov** [comment]
yes, please see `config.h` under #15.

**Comment by fingolfin** [comment]
I cannot reproduce this, and never got the requested data, so I can't do anything about this. If you are still experiencing the issue with GAP 4.10.1, please reopen and provide GAP's `config.h` and `config.log`, as well as the `config.log` of anupq.
