### ISSUE TITLE
ANUPQ standard test (from its PackageInfo.g) hangs

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/anupq#2]
While running 'make testpackages' to run standard tests for GAP packages, ANUPQ hangs forever on two machines with relatively old operating systems

a) x86_64: CentOS release 5.9 (Final), readline 5.1
b) i686: CentOS release 5 (Final), readline 5.1

OTOH, it works well on Ubuntu 12.04 and OS X desktops.

The output from CentOS sometimes short like 

Testing anupq 3.1.1, test=/mnt/disk2/hudson-slave/workspace/GAP-dev-testpackages/GAPCOPTS/32build/GAPGMP/nogmp/GAPTARGET/packages/label/64bit/GAP-dev-snapshot/pkg/anupq-3.1.1/tst/anupqeg.tst, all packages=false

and sometimes full like here

Testing anupq 3.1.1, test=/mnt/disk2/hudson-slave/workspace/GAP-dev-testpackages/GAPCOPTS/32build/GAPGMP/nogmp/GAPTARGET/packages/label/64bit/GAP-dev-snapshot/pkg/anupq-3.1.1/tst/anupqeg.tst, all packages=false
*** glibc detected *** /mnt/disk2/hudson-slave/workspace/GAP-dev-testpackages/GAPCOPTS/32build/GAPGMP/nogmp/GAPTARGET/packages/label/64bit/GAP-dev-snapshot/pkg/anupq-3.1.1/bin/x86_64-unknown-linux-gnu-gcc-default32/pq: free(): invalid pointer: 0x0855385a ***
======= Backtrace: =========
/lib/libc.so.6[0x65ad35]
/lib/libc.so.6(cfree+0x59)[0x65eda9]
/mnt/disk2/hudson-slave/workspace/GAP-dev-testpackages/GAPCOPTS/32build/GAPGMP/nogmp/GAPTARGET/packages/label/64bit/GAP-dev-snapshot/pkg/anupq-3.1.1/bin/x86_64-unknown-linux-gnu-gcc-default32/pq[0x804ac8e]
/mnt/disk2/hudson-slave/workspace/GAP-dev-testpackages/GAPCOPTS/32build/GAPGMP/nogmp/GAPTARGET/packages/label/64bit/GAP-dev-snapshot/pkg/anupq-3.1.1/bin/x86_64-unknown-linux-gnu-gcc-default32/pq[0x805c1ad]
/mnt/disk2/hudson-slave/workspace/GAP-dev-testpackages/GAPCOPTS/32build/GAPGMP/nogmp/GAPTARGET/packages/label/64bit/GAP-dev-snapshot/pkg/anupq-3.1.1/bin/x86_64-unknown-linux-gnu-gcc-default32/pq[0x805e482]
/lib/libc.so.6(__libc_start_main+0xdc)[0x606ebc]
/mnt/disk2/hudson-slave/workspace/GAP-dev-testpackages/GAPCOPTS/32build/GAPGMP/nogmp/GAPTARGET/packages/label/64bit/GAP-dev-snapshot/pkg/anupq-3.1.1/bin/x86_64-unknown-linux-gnu-gcc-default32/pq[0x80490b1]
======= Memory map: ========
005d2000-005ed000 r-xp 00000000 08:11 2301205                            /lib/ld-2.5.so
005ed000-005ee000 r-xp 0001a000 08:11 2301205                            /lib/ld-2.5.so
005ee000-005ef000 rwxp 0001b000 08:11 2301205                            /lib/ld-2.5.so
005f1000-00748000 r-xp 00000000 08:11 2299276                            /lib/libc-2.5.so
00748000-0074a000 r-xp 00157000 08:11 2299276                            /lib/libc-2.5.so
0074a000-0074b000 rwxp 00159000 08:11 2299276                            /lib/libc-2.5.so
0074b000-0074e000 rwxp 0074b000 00:00 0 
00773000-0079a000 r-xp 00000000 08:11 2299356                            /lib/libm-2.5.so
0079a000-0079b000 r-xp 00026000 08:11 2299356                            /lib/libm-2.5.so
0079b000-0079c000 rwxp 00027000 08:11 2299356                            /lib/libm-2.5.so
0079e000-007a9000 r-xp 00000000 08:11 2299341                            /lib/libgcc_s-4.1.2-20080825.so.1
007a9000-007aa000 rwxp 0000a000 08:11 2299341                            /lib/libgcc_s-4.1.2-20080825.so.1
08048000-08076000 r-xp 00000000 08:21 25118097                           /mnt/disk2/hudson-slave/workspace/GAP-dev-testpackages/GAPCOPTS/32build/GAPGMP/nogmp/GAPTARGET/packages/label/64bit/GAP-dev-snapshot/pkg/anupq-3.1.1/bin/x86_64-unknown-linux-gnu-gcc-default32/pq
08076000-08077000 rwxp 0002e000 08:21 25118097                           /mnt/disk2/hudson-slave/workspace/GAP-dev-testpackages/GAPCOPTS/32build/GAPGMP/nogmp/GAPTARGET/packages/label/64bit/GAP-dev-snapshot/pkg/anupq-3.1.1/bin/x86_64-unknown-linux-gnu-gcc-default32/pq
08553000-08574000 rwxp 08553000 00:00 0 
f58f9000-f7f20000 rwxp f58f9000 00:00 0 
f7f20000-f7f53000 r-xp 00000000 08:11 1360154                            /usr/lib/sse2/libgmp.so.3.3.3
f7f53000-f7f54000 rwxp 00032000 08:11 1360154                            /usr/lib/sse2/libgmp.so.3.3.3
f7f7e000-f7f80000 rwxp f7f7e000 00:00 0 
ff91b000-ffa13000 rw-p 7ffffff06000 00:00 0                              [stack]
ffffe000-fffff000 r-xp ffffe000 00:00 0

**Comment by alex-konovalov** [comment]
Thanks! Can't really see how the referenced commit fixes it, but will wait for the next round of weekly tests ;)

**Comment by fingolfin** [comment]
That was a fluke (this was a reference to issue 2 of another repository)

**Comment by alex-konovalov** [comment]
OK ;-) This is stably reproducible. I've assigned to myself to remember to login to that Jenkins OS X slave and run the test with the progress displayed to see where it hangs.

**Comment by alex-konovalov** [comment]
This could be closed indeed as it is superseded by #12 - there is only one configuration reported there where the problem occurs.
