### ISSUE TITLE
PqEpimorphism problem: fp group vs pc group input

### ISSUE THREAD

**Issue by heikodietrich** [gap-packages/anupq#21]
The map returned by PqEpimorphism is not a homomorphism when the input group below is given as a pc-group. It does work when the input group is first translated into an fp-group.

All this came up because we wanted to have a function which, based on StandardPresentation, returns an isomorphism of p-groups. It seems at the moment there's only the function IsIsomorphicPGroup; do you already have a function which does return an actual isomorphism (if exists)?

Cheers,
Heiko

```
LoadPackage("anupq");

Gpc := PcGroupCode(68146375694269006194915807389502420706068560698170186858702642616271311983852576935888031169808724212486427842287695095990141448242086615015179035279810566253194821421235130797478228790709823744504959547811690291508815054696836089975338898421240232146485972558278354047942767460757806879902001011672205506677433540854819814334041631681046533290684225262516467449392593429627898,3^16);


###################################################
epi   := PqEpimorphism(Gpc:Prime:=3);
Gpq   := Image(epi);

IsInjective(epi) and IsSurjective(epi) = true;

gen  := GeneratorsOfGroup(Gpc);;
im   := List(gen, x-> Image(epi,x));;

hom := GroupHomomorphismByImages(Gpc,Gpq, gen, im);
# FAIL!

cnt := 0;
repeat
  cnt := cnt+1;
  a:=Random(Gpc);
  b:=Random(Gpc);
until not Image(epi,a*b) = Image(epi,a)*Image(epi,b);


Image(epi, a*b) = Image(epi,a) * Image(epi,b);
# FALSE!

#####################################################

# now do the same with fp copy of Gpc:

Gfp := FpGroupPcGroup(Gpc);

epi   := PqEpimorphism(Gfp:Prime:=3);
Gpq   := Image(epi);

IsInjective(epi) and IsSurjective(epi) = true;

gen  := GeneratorsOfGroup(Gfp);;
im   := List(gen, x-> Image(epi,x));;

hom := GroupHomomorphismByImages(Gfp,Gpq, gen, im);
# WORKS!
```

**Comment by fingolfin** [comment]
The quotient groups are the same in both cases. So the bug is in how the epimorphism is generated. Tracking through the code, we end up in `PQ_PC_PRESENTATION`, where there is a special case for p-groups, using the `PcgsPCentralSeriesPGroup`. And indeed, this returns the generators, but with g3 and g4 swapped, which matches the bug in the first epimorphism in your example.

So where is the epimorphism constructed? In `PQ_GROUP_FROM_PCP`, with this code:
```
      datarec.pQepi := GroupHomomorphismByImagesNC( 
                           datarec.group,
                           ValueGlobal( "F" ),
                           GeneratorsOfGroup( datarec.group ),
                           ValueGlobal( "MapImages" )
                           );
```
So it is using `GeneratorsOfGroup( datarec.group )` here, which is wrong in our case, where it should be using the pcgs instead. I'll see if I can create a fix for this.

**Comment by heikodietrich** [comment]
Here is a (related?) problem with PqEpimorphism:

########
gap> K:=PcGroupCode(55511293340168776936829128265381835987500000512000655361677721943598263308118596352,1953125);
<pc group of size 1953125 with 9 generators>
gap> T:=PcGroupCode(2000005120000131078710886571799131644676937728,1953125);
<pc group of size 1953125 with 9 generators>
gap> IsIsomorphicPGroup(K,T);
#I  Evaluation in compute_degree may cause integer overflow
Error, pq program terminated, with error condition:
  Evaluation in compute_degree may cause integer overflow
 at /daten/gap-4.10.0/pkg/anupq-3.2/lib/anupqios.gi:484 called from
FILTER_PQ_STREAM_UNTIL_PROMPT( datarec ); at /daten/gap-4.10.0/pkg/anupq-3.2/lib/anupqios.gi:630 called from
ToPQ( datarec, [ 0 ], [ "  #do not ", comment ] ); at /daten/gap-4.10.0/pkg/anupq-3.2/lib/anupqios.gi:658 called from
ToPQ_BOOL( datarec, VALUE_PQ_OPTION( "PcgsAutomorphisms", false, datarec ), "compute pcgs gen. seq. for auts." ); at /daten/gap-4.10.0/pkg/anupq-3.2/lib/anupqi.gi:2439 called from
PQ_SP_STANDARD_PRESENTATION( datarec ); at /daten/gap-4.10.0/pkg/anupq-3.2/lib/anusp.gi:197 called from
PQ_EPIMORPHISM_STANDARD_PRESENTATION( arg ) at /daten/gap-4.10.0/pkg/anupq-3.2/lib/anusp.gi:253 called from
...  at *stdin*:19
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk>
#######

Once I also got the following error message, but I cannot reproduce this:

> gap> IsIsomorphicPGroup(K,T);
> Error, PrintTo: cannot open '/var/folders/bz/2vgplf091k76j_fyhl3g2s05gwbdyt/T//tmAcQb\
> Ul/GAP_library' for output in
>   CallFuncList( PRINT_TO, arg ); at /daten/gap-4.10.0/lib/streams.gd:1044 called from
> PrintTo( ANUPQData.SPimages, ""
>  ); at /daten/gap-4.10.0/pkg/anupq-3.2/lib/anupqios.gi:25 called from
> PQ_START( VALUE_PQ_OPTION( "PqWorkspace", 10000000 ),
>  VALUE_PQ_OPTION( "SetupFile" )
>  ) at /daten/gap-4.10.0/pkg/anupq-3.2/lib/anupqios.gi:824 called from
> ANUPQ_ARG_CHK( "StandardPresentation", args
>  ) at /daten/gap-4.10.0/pkg/anupq-3.2/lib/anusp.gi:137 called from
> PQ_EPIMORPHISM_STANDARD_PRESENTATION( arg
>  ) at /daten/gap-4.10.0/pkg/anupq-3.2/lib/anusp.gi:253 called from
> PqStandardPresentation( PqFpGroupPcGroup( G )
>  ) at /daten/gap-4.10.0/pkg/anupq-3.2/lib/anusp.gi:343 called from
> ...  at *stdin*:4
> #I  Options stack has been reset

**Comment by fingolfin** [comment]
These are not related. For

For organizational purpose (i.e. to not get me confused, resulting in issues being overlooked), it is best to open separate issues for each problem you encounter, unless you are 95% certain they have the same cause. So I made a new issue #32 with your comment above.
