### ISSUE TITLE
License declaration is missing

### ISSUE THREAD

**Issue by jengelh** [gap-packages/anupq#25]
The package does not have a declaration of what license applies. Just the name would be enough for my needs, but even that is missing. This makes it impossible to distribute with Linux distributions.
Methods that were tried to find any declaration: locate a file whose name matches /copying/i, locate a file whose name matches /license/, locate a file /readme/ which mentions the word /license/i, locate any non-autogenerated file containing the words /gnu.general/i or /warranty/i.

**Comment by jengelh** [comment]
The ANUPQ 3.2 release is still missing a suitable declaration.

**Comment by jamesjer** [comment]
I would also like to know what license this code is distributed under.

**Comment by alex-konovalov** [comment]
+1

**Comment by fingolfin** [comment]
I've emailed Eamon O'Brien to resolve this

**Comment by fingolfin** [comment]
After discussions with Greg Gamble, Werner Nickel, and Eamon O'Brien, it was agreed to license anupq under the Artistic License 2.0. See PR #58

**Comment by jamesjer** [comment]
Thank you for handling this @fingolfin .
