### ISSUE TITLE
Unresolved links to main GAP manuals

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/anupq#3]
FYI, the following links in the Anupq manuals are not resolved:

badlink:ref:IsConfluent!for pc groups
  used in 2 files:
  /pkg/anupq-3.1.1/htm/CHAP004.htm
  /pkg/anupq-3.1.1/htm/CHAP005.htm

badlink:ref:The .gaprc file
  used in 1 file:
  /pkg/anupq-3.1.1/htm/CHAP003.htm

badlink:ref:function call!with options
  used in 2 files:
  /pkg/anupq-3.1.1/htm/CHAP004.htm
  /pkg/anupq-3.1.1/htm/CHAP005.htm

**Comment by fingolfin** [comment]
This is out of date, the manual was rewritten in GAPDoc.
