### ISSUE TITLE
 relict from translated GAP3 code

### ISSUE THREAD

**Issue by heikodietrich** [gap-packages/anupq#9]
Sporadically I receive the error below; unfortunately, it's not easy to provide code which reproduces it:

> > Error, illegal access to record component `obj.27'
> > of the object <obj>. (Objects by default do not have record components.
> > The error might be a relic from translated GAP3 code.)       called from
> > G.2 \* G.15 \* G.16 ^ 4 \* G.17 ^ 4 \* G.18 ^ 5 \* G.19 ^ 5 \* G.22 \* G.23 ^ 5
> > - G.24 ^ 2 \* G.26 ^ 4 called from
> >   autos[func](lst[Length%28 lst %29]); called from
> >   PqList( Filename( ANUPQData.tmpdir, "GAP_library" ) ) called from
> >   PQ_DESCENDANTS( arg ) called from
> >   PqDescendants( d ) called from
> >   ...  at line 1 of _stdin_
> > #### 

Since an appropriate error message is given, it would be great if one could take care that this error does actually not happen... could this be done easily?

For the input: I apply PqDescendants recursively to groups which I have constructed with PqDescendants -- starting with a group computed by Pq.

**Comment by fingolfin** [comment]
I am not so sure this is a "relic"... that may or may not be true, but let's not by accident be lead onto a wrong track ;-). After all, even in GAP 4 it is possible (and I frequently use this) to access the generators of many group objects via `G.1`, `G.2`, etc.

**Comment by fingolfin** [comment]
BTW, if you have any concrete example to reproduce the issue, which you can post here, that would greatly help with debugging the cause

**Comment by alex-konovalov** [comment]
Could it be that some previous example failed and after that `.` access was tried on an object on which it was not supposed to be called? I have seen that trying to build a test file for `cohomolo` last week.

**Comment by fingolfin** [comment]
@alex-konovalov perhaps. Although, given the trace excerpt @heikodietrich provides, it might also be case of a group with 26 generators, where for some reason (i.e. a bug) some code tried to access the (non-existent) 27th generator via the `G.27` syntax. This is supported by the fact that trace output Heiko gave lists access to generators in this style, though only up to `G.26`

In so far, the report about the "relict from translated GAP3 code" is most likely a red herring.

**Comment by fingolfin** [comment]
Without any way for me to reproduce this, in particular, no test case, there is nothing I can do about this. Feel free to reopen with a testcase (even a slow one or whatever) if you can still reproduce this.
